{"name": "发起正常报备", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'", "trace": "self = <pages.workplace_page.recruit_page.recruit_page.Recruit object at 0x0404BCA0>\nloc = ('xpath', \"//*[@class='ant-message-custom-content ant-message-success']/span\")\nexpect = '上传成功！1111'\n\n    def assert_text(self,loc,expect):\n        logging.info('断言有无{}'.format(expect))\n        try:\n>           assert expect in self.locator(loc).text\nE           AssertionError\n\nbase\\base_page.py:48: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nremote_driver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"7133858d4eb55a8282a5785140dbb93e\")>\n\n    @pytest.mark.run(order=3)\n    @pytest.mark.workspace\n    @allure.feature(\"正常报备\")\n    @allure.story(\"发起正常报备\")\n    @allure.title(\"发起正常报备\")\n    def test_03(remote_driver):\n        wp=WorkPlace(remote_driver)\n        re=Recruit(remote_driver)\n        wp.open_recruit()\n>       re.normal_report(3)\n\ncases\\test_case_pytest.py:103: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\workplace_page\\recruit_page\\recruit_page.py:60: in normal_report\n    self.assert_text(self.tips,'上传成功！1111')\nbase\\base_page.py:54: in assert_text\n    allure.attach(self.screen_short())\nd:\\工具\\python\\lib\\site-packages\\allure_commons\\_allure.py:179: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\nd:\\工具\\python\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nd:\\工具\\python\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nd:\\工具\\python\\lib\\site-packages\\allure_pytest\\listener.py:222: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\nd:\\工具\\python\\lib\\site-packages\\allure_commons\\reporter.py:119: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\nd:\\工具\\python\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nd:\\工具\\python\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.logger.AllureFileLogger object at 0x038484F0>\nbody = None\nfile_name = 'f2b22b27-5af3-4ed2-8f9f-2ebd9fa4b2a4-attachment.attach'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = os.path.join(self._report_dir, file_name)\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, text_type):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'NoneType'\n\nd:\\工具\\python\\lib\\site-packages\\allure_commons\\logger.py:62: TypeError"}, "description": "招聘管理", "steps": [{"name": "招聘中心", "status": "passed", "start": 1657610135584, "stop": 1657610138612}, {"name": "我要报备", "status": "passed", "start": 1657610138612, "stop": 1657610140585}, {"name": "点击需求框", "status": "passed", "start": 1657610140586, "stop": 1657610142730}, {"name": "选择报备测试", "status": "passed", "start": 1657610142731, "stop": 1657610143626}, {"name": "下一步", "status": "passed", "start": 1657610143626, "stop": 1657610144616}, {"name": "执行脚本生成正常报备数据", "status": "passed", "start": 1657610144616, "stop": 1657610145880}, {"name": "上传文件", "status": "passed", "start": 1657610145880, "stop": 1657610148088}, {"name": "下一步", "status": "passed", "attachments": [{"source": "2e137ef4-fa8d-4448-93ed-9672ecaf1bad-attachment.attach"}], "start": 1657610148088, "stop": 1657610150603}, {"name": "断言", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"D:\\selenium_compass\\pages\\workplace_page\\recruit_page\\recruit_page.py\", line 60, in normal_report\n    self.assert_text(self.tips,'上传成功！1111')\n  File \"D:\\selenium_compass\\base\\base_page.py\", line 54, in assert_text\n    allure.attach(self.screen_short())\n  File \"d:\\工具\\python\\lib\\site-packages\\allure_commons\\_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\工具\\python\\lib\\site-packages\\allure_pytest\\listener.py\", line 222, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"d:\\工具\\python\\lib\\site-packages\\allure_commons\\reporter.py\", line 119, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\工具\\python\\lib\\site-packages\\allure_commons\\logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"source": "f2b22b27-5af3-4ed2-8f9f-2ebd9fa4b2a4-attachment.attach"}], "start": 1657610150603, "stop": 1657610152183}], "attachments": [{"name": "log", "source": "a21fa02b-f65f-4529-9a05-bd7ba175b4fb-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "9f2f6e24-3a9a-4432-a091-eb3428bd8c15-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ddb19611-3c43-4b37-8783-fed2cfe7c3f8-attachment.txt", "type": "text/plain"}], "start": 1657610132771, "stop": 1657610152208, "uuid": "1cd986aa-196d-4dc8-9a83-9e59f70dc180", "historyId": "16f22687593725c12106086be8d125a7", "testCaseId": "87b97e7b3c0856482c474c743a54111f", "fullName": "cases.test_case_pytest#test_03", "labels": [{"name": "feature", "value": "正常报备"}, {"name": "story", "value": "发起正常报备"}, {"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "workspace"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_case_pytest"}, {"name": "host", "value": "LAPTOP-5D6NI12E"}, {"name": "thread", "value": "980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_case_pytest"}]}