{"uuid": "18f491aa-2241-4307-a912-6f1c21403382", "children": ["d65b4864-f18d-4824-9fa4-eae966c378ff", "b792db08-0207-43e1-a9b3-75e0e7fb7e36", "ab74963c-785f-4abe-af56-03731a699ce1", "dfb5ba3d-10c2-4075-9a66-73bc844a8915"], "befores": [{"name": "remote_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=103.0.5060.66)\nBuild info: version: '4.2.2', revision: '683ccb65d6'\nSystem info: host: 'LAPTOP-5D6NI12E', ip: '192.168.7.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: unknown\nBuild info: version: '4.2.2', revision: '683ccb65d6'\nSystem info: host: 'LAPTOP-5D6NI12E', ip: '192.168.7.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: unknown\nBuild info: version: '4.2.2', revision: '683ccb65d6'\nSystem info: host: 'LAPTOP-5D6NI12E', ip: '192.168.7.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: unknown\nStacktrace:\n    at org.openqa.selenium.grid.node.remote.RemoteNode.newSession (RemoteNode.java:150)\n    at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession (LocalDistributor.java:618)\n    at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession (LocalDistributor.java:544)\n    at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest (LocalDistributor.java:791)\n    at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1 (LocalDistributor.java:752)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)\n    at java.lang.Thread.run (None:-1)\n", "trace": "  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\工具\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\工具\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\auto_test\\case\\test_case_pytest.py\", line 28, in remote_driver\n    driver = webdriver.Remote('http://127.0.0.1:4444/wd/hub',desired_caps)\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1657033825237, "stop": 1657033850560}], "start": 1657033825237, "stop": 1657033850910}